version: '3.7'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - "php"
    volumes:
      - "$PWD/conf.d:/etc/nginx/conf.d"
      - "$PWD/src:/var/www/html"
    networks:
      - app_net
    # 容器名称
    container_name: "dnmp_nginx"
  php:
    build: ./php_mysqli
      # image指定build Dockerfile生成镜像的名称
    image: php:latest-fpm-mysqli
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/src:/var/www/html"
    networks:
      - app_net
    container_name: "dnmp_php"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    networks:
      app_net:
        ipv4_address: 10.10.10.1
    container_name: "dnmp_mysql"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16