version: '3.7'
services:
  nginx:
    # 直接使用官方image
    # 格式  image:tag
    image: nginx:alpine

    # 主機port : container port
    ports:
      - "8080:80"
    depends_on:
      - "php"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./src:/var/www/html"
    networks:
      - app_net
    # docker exec -it dnmp_nginx sh
    container_name: "dnmp_nginx"
  php:
    # 指定要用來build的Dockerfile
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - "./src:/var/www/html"
    networks:
      - app_net
    container_name: "dnmp_php"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    networks:
      app_net:
        ipv4_address: 10.10.10.1
    container_name: "dnmp_mysql"
  redis:
    # using specified redis conf
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/data:/data"
    networks:
      app_net:
        ipv4_address: 10.10.10.2
    container_name: "dnmp_redis"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16